name: ciFAIR
title: ciFAIR
description: A duplicate-free variant of the CIFAR test set.
exclude: [README.md]
theme: jekyll-theme-tactile

show_downloads: true
owner_logo: /assets/images/cvjena-logo.png
github:
  owner_url: http://www.inf-cv.uni-jena.de/