name: ciFAIR
title: ciFAIR
description: A duplicate-free variant of the CIFAR test set.
exclude: [README.md]
theme: jekyll-theme-tactile

show_downloads: true
google_analytics: UA-25984997-7
owner_logo: /assets/images/cvjena-logo.png
paper:
  title: Do We Train on Test Data? Purging CIFAR of Near-Duplicates.
  authors: Björn Barz and Joachim Denzler
  venue: Journal of Imaging, 6(6):41
  year: 2020
  url: https://arxiv.org/pdf/1902.00423
github:
  owner_url: http://www.inf-cv.uni-jena.de/
